global trajectories_dict
global df_network
global df_bridges
global df_terminal
global df_passages
global vessels_dict
global moving_vessels
global environment
global draw_scale
global zoomed
global detailed_map
global draw_trajectories
